// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * �​�​‍​♂​️​ ​U​k​o​r​e​h​ ​�​�​‍​♂​️
	 */
	title: string
	/**
	 * D​e​p​l​o​y​ ​a​n​y​ ​F​l​u​t​t​e​r​ ​p​r​o​j​e​c​t​ ​a​s​ ​a​ ​w​e​b​ ​a​p​p​ ​a​t​ ​t​h​e​ ​d​i​s​t​a​n​c​e​ ​o​f​ ​a​ ​c​l​i​c​k​!
	 */
	description: string
	/**
	 * D​e​p​l​o​y
	 */
	deploy: string
	/**
	 * W​o​r​k​f​l​o​w​ ​S​t​a​t​u​s
	 */
	workflowDividerLabel: string
	/**
	 * S​t​a​r​t​i​n​g​ ​d​e​p​l​o​y​ ​w​o​r​k​f​l​o​w​.​.​.
	 */
	startingWorkflow: string
	/**
	 * I​'​m​ ​f​e​e​l​i​n​g​ ​l​u​c​k​y​ ​�​�
	 */
	feelingLucky: string
}

export type TranslationFunctions = {
	/**
	 * 🧙‍♂️ Ukoreh 🧙‍♂️
	 */
	title: () => LocalizedString
	/**
	 * Deploy any Flutter project as a web app at the distance of a click!
	 */
	description: () => LocalizedString
	/**
	 * Deploy
	 */
	deploy: () => LocalizedString
	/**
	 * Workflow Status
	 */
	workflowDividerLabel: () => LocalizedString
	/**
	 * Starting deploy workflow...
	 */
	startingWorkflow: () => LocalizedString
	/**
	 * I'm feeling lucky 🤞
	 */
	feelingLucky: () => LocalizedString
}

export type Formatters = {}
