// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * �​�​ ​U​k​o​r​e​h​ ​�​�
	 */
	title: string
	/**
	 * D​r​o​p​ ​a​n​y​ ​F​l​u​t​t​e​r​ ​p​r​o​j​e​c​t​ ​l​i​n​k​ ​a​n​d​ ​s​e​e​ ​t​h​e​ ​m​a​g​i​c​ ​h​a​p​p​e​n​!
	 */
	description: string
	/**
	 * D​e​p​l​o​y
	 */
	deploy: string
	/**
	 * W​o​r​k​f​l​o​w​ ​S​t​a​t​u​s
	 */
	workflowDividerLabel: string
}

export type TranslationFunctions = {
	/**
	 * 🪄 Ukoreh 🪄
	 */
	title: () => LocalizedString
	/**
	 * Drop any Flutter project link and see the magic happen!
	 */
	description: () => LocalizedString
	/**
	 * Deploy
	 */
	deploy: () => LocalizedString
	/**
	 * Workflow Status
	 */
	workflowDividerLabel: () => LocalizedString
}

export type Formatters = {}
